name: Build Frontend

on:
  push:
    paths:
      - "client/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build frontend (Vite)
        working-directory: ./client
        run: |
          npm install
          npm run build
